http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline
xpack.monitoring.elasticsearch.url: http://elasticsearch:9200
modules:
- name: netflow
  var.elasticsearch.hosts: "http://elasticsearch:9200"
  var.input.tcp.port: 2055
